### ISSUE TITLE
Palestine MoTA national instance - TODO

### ISSUE THREAD

**Issue by zoometh** [eamena-project/eamena-arches-dev#35]
- [ ] clean the HP (Jordan locations)
- [ ] modify the incrementor function
- [ ] remove People/Organisation not linked with Palestinian ressources
